name: Webhook Triggered Build

on:
  repository_dispatch:
    types: [runner-images-updated]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA from Microsoft runner-images'
        required: true
        default: ''

jobs:
  build-runners:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ubuntu-version: ['24.04']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Initialize submodules
        run: |
          echo "Initializing submodules..."
          git submodule update --init --recursive
          echo "Submodule status:"
          git submodule status
      
      - name: Verify submodule structure
        run: |
          echo "Verifying submodule structure..."
          if [ ! -d "runner-images" ]; then
            echo "ERROR: runner-images submodule not found!"
            exit 1
          fi
          if [ ! -d "runner-images/images/ubuntu" ]; then
            echo "ERROR: Ubuntu images directory not found in submodule!"
            exit 1
          fi
          echo "✓ Submodule structure verified"
          ls -la runner-images/images/ubuntu/
      
      - name: Update submodule to specific commit
        if: github.event.inputs.commit_sha != ''
        run: |
          cd runner-images
          git fetch origin
          git checkout ${{ github.event.inputs.commit_sha }}
          cd ..
          git add runner-images
          git commit -m "Update runner-images submodule to ${{ github.event.inputs.commit_sha }}"
          git push
      
      - name: Generate Dockerfiles
        run: |
          echo "Generating Dockerfiles from Microsoft's runner-images..."
          chmod +x scripts/generate-dockerfiles.sh
          ./scripts/generate-dockerfiles.sh
          echo "✓ Dockerfiles generated"
          ls -la dockerfiles/ubuntu/24.04/
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Ubuntu ${{ matrix.ubuntu-version }} runner
        run: |
          cd dockerfiles/ubuntu/${{ matrix.ubuntu-version }}
          docker build -t skunklabz/ubuntu-${{ matrix.ubuntu-version }}-runner:latest .
          
          # Tag with commit SHA if provided, otherwise use current submodule commit
          if [ "${{ github.event.inputs.commit_sha }}" != "" ]; then
            COMMIT_SHA="${{ github.event.inputs.commit_sha }}"
          else
            COMMIT_SHA=$(git submodule status --cached | grep "runner-images" | awk '{print $1}')
          fi
          
          docker tag skunklabz/ubuntu-${{ matrix.ubuntu-version }}-runner:latest skunklabz/ubuntu-${{ matrix.ubuntu-version }}-runner:$COMMIT_SHA
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push Docker images
        run: |
          docker push skunklabz/ubuntu-${{ matrix.ubuntu-version }}-runner:latest
          
          if [ "${{ github.event.inputs.commit_sha }}" != "" ]; then
            COMMIT_SHA="${{ github.event.inputs.commit_sha }}"
          else
            COMMIT_SHA=$(git submodule status --cached | grep "runner-images" | awk '{print $1}')
          fi
          
          docker push skunklabz/ubuntu-${{ matrix.ubuntu-version }}-runner:$COMMIT_SHA
